#ifndef  __PPTSWITCHDOOR_KSWITCHSTYLE_H__
#define __PPTSWITCHDOOR_KSWITCHSTYLE_H__

const enum SWITCHSTYLE
{
	SWITCHSTYLE_NONE = -1,
	SWITCHSTYLE_DOOR,
	SWITCHSTYLE_PRESTIGE,
	SWITCHSTYLE_CURTAIN
};

#endif //__PPTSWITCHDOOR_KSWITCHSTYLE_H__